services:
  schedule-bot:
    image: schedule_bot:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule_bot
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

