version: '3.8'

services:
  schedule-bot:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - AIRTABLE_APIKEY=${AIRTABLE_APIKEY}
      - AIRTABLE_BASEID=${AIRTABLE_BASEID}