name: Deploy Bot to VPS

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  checkout:
    runs-on: ubuntu-latest
    outputs:
      bot_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Bot Version from Tag
        id: get_version
        run: |
          # Extract the GitHub tag version
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "Version extracted: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Archive project files
        uses: actions/upload-artifact@v4
        with:
          name: project-files
          path: .

  notify_start:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Notify Deployment Start
        run: |
          start_msg="🚀 Deployment Start for: <code>${{ github.repository }}</code> on branch <code>${{ github.ref_name }}</code>%0A☑️Version: <code>${{ needs.checkout.outputs.bot_version }}</code>"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.NOTIFY_BOT_TOKEN }}/sendMessage" \
            --data-urlencode "chat_id=${{ vars.IT_TELEGRAM_CHAT_ID }}" \
            --data-urlencode "text=${start_msg}" \
            --data-urlencode "message_thread_id=${{ vars.IT_TELEGRAM_CHAT_NOTIFY_TOPIC_ID }}" \
            --data-urlencode "parse_mode=HTML"
  copy:
    needs: notify_start
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/download-artifact@v4
        with:
          pattern: project-files
          merge-multiple: true

      - name: Copy project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: ~/Catebi.ScheduleBot

  build_deploy:
    needs: [copy, checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Catebi.ScheduleBot
            echo "Updating .env file..."
            cat <<EOF > .env
            API_ID=${{ secrets.TELEGRAM_API_ID }}
            API_HASH=${{ secrets.TELEGRAM_API_HASH }}
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            AIRTABLE_API_KEY=${{ secrets.AIRTABLE_APIKEY }}
            AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASEID }}
            AIRTABLE_STERILIZATION_BASE_ID=${{ secrets.AIRTABLE_STERILIZATION_BASEID }}
            VERSION=${{ needs.checkout.outputs.bot_version }}
            EOF
            echo "Pulling Docker images..."
            docker-compose down
            docker-compose up --build -d

  notify_finish:
    needs: [checkout, notify_start, copy, build_deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Deployment Success
        if: success()
        run: |
          msg="✅ Successful Deployment passed:%0A🤖<code>${{ github.repository }}</code> at <code>${{ github.sha }}</code>%0A☑️Version: <code>${{ needs.checkout.outputs.bot_version }}</code>"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.NOTIFY_BOT_TOKEN }}/sendMessage" \
          --data-urlencode "chat_id=${{ vars.IT_TELEGRAM_CHAT_ID }}" \
          --data-urlencode "text=${start_msg}" \
          --data-urlencode "message_thread_id=${{ vars.IT_TELEGRAM_CHAT_NOTIFY_TOPIC_ID }}" \
          --data-urlencode "parse_mode=HTML"

      - name: Notify Deployment Failure
        if: failure()
        run: |
          failure_msg="❌ Deployment Failed: Check the actions log for details.%0AView Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}%0A☑️Version: <code>${{ needs.checkout.outputs.bot_version }}</code>"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.NOTIFY_BOT_TOKEN }}/sendMessage" \
          --data-urlencode "chat_id=${{ vars.IT_TELEGRAM_CHAT_ID }}" \
          --data-urlencode "text=${failure_msg}" \
          --data-urlencode "message_thread_id=${{ vars.IT_TELEGRAM_CHAT_NOTIFY_TOPIC_ID }}" \
          --data-urlencode "parse_mode=HTML"