name: Deploy Bot to VPS

on:
  push:
    branches:
      - feature/#1_ci_cd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # copy files to the VPS
      - name: Copy project files
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: ~/Catebi.ScheduleBot

      # deploy and restart using docker-compose
      - name: Deploy and restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Catebi.ScheduleBot
            echo "Updating .env file..."
            cat <<EOF > .env
            TELEGRAM_API_ID=${{ secrets.TELEGRAM_API_ID }}
            TELEGRAM_API_HASH=${{ secrets.TELEGRAM_API_HASH }}
            BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            AIRTABLE_API_KEY=${{ secrets.AIRTABLE_APIKEY }}
            AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASEID }}
            EOF
            echo "Pulling Docker images..."
            docker-compose down
            docker-compose up -d